(define (problem prueba_de_fuego_3) 
(:domain port)
(:objects
box1 box2 box3 dock1 dock2 pallet1 pallet2 crane1 crane2 cinta - box
n0 n1 n2 n3 - height
)

(:init
    ;todo: put the initial state's facts and numeric values here
    (movable box1)
    (movable box2)
    (movable box3)
    (top box1)
    (top crane1)
    (top crane2)
    (top cinta)
    (top pallet2)
    (at crane1 crane1)
    (at crane2 crane2)
    (at cinta cinta)
    (at pallet1 dock1)
    (at pallet2 dock2)
    (at box1 dock1)
    (at box2 dock1)
    (at box3 dock1)
    (on box1 box2)
    (on box2 box3)
    (on box3 pallet1)
    (next n0 n1)
    (next n1 n2)
    (next n2 n3)
    (link crane1 dock1)
    (link dock1 crane1)
    (link crane2 dock2)
    (link dock2 crane2)
    (link crane1 cinta)
    (link cinta crane1)
    (link crane2 cinta)
    (link cinta crane2)
    (max_height crane1 n1)
    (max_height crane2 n1)
    (max_height dock1 n3)
    (max_height dock2 n3)
    (max_height cinta n1)
    (height pallet1 n0)
    (height pallet2 n0)
    (height crane1 n0)
    (height crane2 n0)
    (height cinta n0)
    (height box1 n3)
    (height box2 n2)
    (height box3 n1)
)

(:goal (and
    (on box3 box2)
    (on box2 box1)
    ;(at box1 dock2)
))

)
