(define (problem prueba_de_fuego_3) 
(:domain port)
(:objects
box1 box2 dock1 dock2 pallet1 pallet2 crane1 crane2 poscinta11 poscinta12 poscinta21 poscinta22 - box
n0 n1 n2 n3 - height
)

(:init
    ;todo: put the initial state's facts and numeric values here
    (green box1)
    (ready box1 dock1)
    (ready box2 dock2)
    (movable box2)
    (top box1)
    (top box2)
    (top crane1)
    (top crane2)
    (top poscinta11)
    (top poscinta12)
    (top poscinta21)
    (top poscinta22)
    (at crane1 crane1)
    (at crane2 crane2)
    (at poscinta11 poscinta11)
    (at poscinta12 poscinta12)
    (at poscinta21 poscinta21)
    (at poscinta22 poscinta22)
    (at pallet1 dock1)
    (at pallet2 dock2)
    (at box1 dock1)
    (at box2 dock2)
    (on box1 pallet1)
    (on box2 pallet2)
    (next n0 n1)
    (next n1 n2)
    (next n2 n3)
    (link poscinta11 poscinta12)
    (link poscinta22 poscinta21)
    (link crane1 dock1)
    (link crane1 poscinta11)
    (link crane1 poscinta21)
    (link poscinta11 crane1)
    (link poscinta21 crane1)
    (link crane2 poscinta12)
    (link crane2 poscinta22)
    (link poscinta12 crane2)
    (link poscinta22 crane2)
    (link dock1 crane1)
    (link crane2 dock2)
    (link dock2 crane2)
    (max_height crane1 n1)
    (max_height crane2 n1)
    (max_height dock1 n3)
    (max_height dock2 n3)
    (max_height poscinta11 n1)
    (max_height poscinta12 n1)
    (max_height poscinta21 n1)
    (max_height poscinta22 n1)
    (height pallet1 n0)
    (height pallet2 n0)
    (height crane1 n0)
    (height crane2 n0)
    (height poscinta11 n0)
    (height poscinta12 n0)
    (height poscinta21 n0)
    (height poscinta22 n0)
    (height box1 n1)
    (height box2 n1)
)

(:goal (and
    (ready box2 dock1)
))

)
