(define (problem prueba_de_fuego_2) 
(:domain port)
(:objects
box1 box2 dock1 dock2 pallet1 pallet2 crane1 crane2 cinta - box
n0 n1 n2 - height
)

(:init
    ;todo: put the initial state's facts and numeric values here
    (movable box1)
    (movable box2)
    (top box1)
    (top box2)
    (top crane1)
    (top crane2)
    (top cinta)
    (at crane1 crane1)
    (at crane2 crane2)
    (at cinta cinta)
    (at pallet1 dock1)
    (at pallet2 dock2)
    (at box1 dock1)
    (at box2 dock2)
    (on box1 pallet1)
    (on box2 pallet2)
    (next n0 n1)
    (next n1 n2)
    (link crane1 dock1)
    (link dock1 crane1)
    (link crane2 dock2)
    (link dock2 crane2)
    (link crane1 cinta)
    (link cinta crane1)
    (link crane2 cinta)
    (link cinta crane2)
    (max_height crane1 n1)
    (max_height crane2 n1)
    (max_height dock1 n2)
    (max_height dock2 n2)
    (max_height cinta n1)
    (height pallet1 n0)
    (height pallet2 n0)
    (height crane1 n0)
    (height crane2 n0)
    (height cinta n0)
    (height box1 n1)
    (height box2 n1)
)

(:goal (and
    (on box2 box1)
))

)
